sudo: required

services:
  - docker

language: node_js

node_js:
  - "6"

install:
  - npm install -g dockerlint

script: 
  - dockerlint Dockerfile
  - docker build -t nginx .
  - docker run -d -p 127.0.0.1:80:80 --name nginx nginx
  - docker ps | grep -q nginx
  - curl -vsf 'http://127.0.0.1:80/' &> /dev/stdout
  - curl -vsf -H 'Accept-Encoding: gzip' 'http://127.0.0.1:80/' &> /dev/stdout | grep -i 'Content-Encoding: gzip'
