sudo: required

services:
  - docker

language: node_js

node_js:
  - "6"

install:
  - npm install -g dockerlint
  - docker build -t nginx .
  - docker run -d -p 127.0.0.1:80:80 --name nginx nginx

script: 
  - dockerlint Dockerfile
  - docker ps | grep -q nginx
